#!/usr/bin/python
import json
import subprocess
from distutils.version import LooseVersion

p = subprocess.Popen(["oarnodes", "-J"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
(out, err) = p.communicate()
oarnodes = json.loads(out)
res = []
for _,v in oarnodes.iteritems():
    if "jobs" not in v:
        res.append("{} {}".format(v["host"], v["state"]))

res.sort(key=LooseVersion)

print "\n".join(res)
