#!/usr/bin/python
import re
import subprocess

p = subprocess.Popen(["oarstat"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
(oarstat, err) = p.communicate()

jobs = {}
regex =  re.compile(".*P=([A-Z]+)")
for line in oarstat.split('\n'):
    m = regex.match(line)
    if m:
        if m.group(1) in jobs:
            jobs[m.group(1)] = jobs[m.group(1)] + 1
        else:
            jobs[m.group(1)] = 1

for k, v in jobs.iteritems():
    print k, v
